spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tienda_camisas
    username: tienda_user
    password: contra
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
